### PR TITLE
Adding RECAPTCHA_DISABLE to disable recaptcha

### PR DESCRIPTION
**Pull request by rnt**
This pull request allows you to use forms, without commenting on the recaptcha field when you are offline.

### CODE REVIEW

**Comment by rnt** [comment]
Hi @lepture,

Its possible to release a new version with this patch?
:)

Thanks!

**Comment by lepture** [comment]
If you are in development mode. You can use Flask TESTING mode.

**Comment by rnt** [comment]
@lepture:
Enable flask TESTING mode is an option, yes.
But do not want disable the error catching when I'm programming offline.

The purpose of the patch is able to separate these behaviors.

**Comment by ErikThoreson** [comment]
+1 

would really like to see this merged.

**Comment by rnt** [comment]
@vin01 @ErikThoreson see #509 ;)

**Pull request closed without merging**
