### PR TITLE
[Review needed] Added `i18n` support to local messages.

### PR DESCRIPTION
**Pull request by sobolevn**
List of major changes:
1. Added `babel` and `speaklater` as development dependencies
2. Added `flask_wtf/locale` folder, with `en` and `ru` locales
3. Added `flask_wtf/locale/README.md` on how to work with it
4. Changed `MANIFEST.in` to include locales
5. Changed `setup.cfg` to configure `babel`
6. Changed tests

### CODE REVIEW

**Comment by sobolevn** [comment]
Travis build fails for some reason, locally it passes:

> (flaskwtf) [16:18:17] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/flask-wtf ‹master*› » python setup.py nosetests -s
> running nosetests
> running egg_info
> writing requirements to Flask_WTF.egg-info/requires.txt
> writing Flask_WTF.egg-info/PKG-INFO
> writing top-level names to Flask_WTF.egg-info/top_level.txt
> writing dependency_links to Flask_WTF.egg-info/dependency_links.txt
> reading manifest file 'Flask_WTF.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '*.pyo' found under directory 'tests'
> no previously-included directories found matching 'docs/_build'
> warning: no previously-included files found matching 'docs/_themes/.git*'
> warning: no previously-included files matching '*.pyc' found under directory 'docs'
> warning: no previously-included files matching '*.pyo' found under directory 'docs'
> writing manifest file 'Flask_WTF.egg-info/SOURCES.txt'
> ...................................................
> ----------------------------------------------------------------------
> Ran 52 tests in 0.718s
> 
> OK

**Comment by sobolevn** [comment]
Seems like I have missed to add `speaklater` to `requirements.txt`.

**Comment by sobolevn** [comment]
@davidism @lepture Any feedback please?

**Comment by lipis** [comment]
Let's avoid using the translations in the core repo.. and put them in [Crowdin](https://crowdin.com) project to have all the translations that we want there. It's hard to maintain and there is no need to have 200 languages in the repo when in most cases you don't need and sometimes you just need a few.. Plus on Crowdin you can host for free, for open source projects!

**Comment by sobolevn** [comment]
@lipis I really like that! Let's wait for the maintainers response.

**Pull request closed without merging**
